Echo instead of notification

diff --git a/scripts/bin/taskcount b/scripts/bin/taskcount
--- a/scripts/bin/taskcount
+++ b/scripts/bin/taskcount
@@ -15,11 +15,8 @@ synctasks() {
 	cp "$HOME/.local/share/task/"{completed,pending}".data" "/tmp/task.bak/"
 	syncoutput=$($synccmd 2>&1)
 	if [[ $? -ne 0 ]]; then
-		syncoutput=$($synccmd 2>&1)
-		if [[ $? -ne 0 ]]; then
-			notify-send 'Task sync failed.'
-			exit
-		fi
+		echo 'Task sync failed.'
+		exit 1
 	fi
 	if [[ $(grep -c -m1 'Sync successful. No changes.' <<< $syncoutput) -ge 1 ]]; then
 		[[ -e /tmp/task.bak ]] && rm -r /tmp/task.bak
@@ -33,7 +30,6 @@ synctasks() {
 		original="$HOME/.local/share/task/${name}.data"
 		old="/tmp/task.bak/${name}.data"
 		diff $original $old >> $logfile
-		# dwdiff -C0 -l $original $old
 		echo -e '\n\n' >> $logfile
 	done
 
